# Generated by Django 4.1.4 on 2023-07-30 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="decription",
            new_name="description",
        ),
    ]
