# Generated by Django 4.1.4 on 2023-07-30 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("task_app", "0003_chaange_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaange_request",
            name="creator",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creator",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
